# Generated by Django 2.1.7 on 2019-03-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_ID', models.IntegerField()),
                ('certNumber', models.IntegerField()),
                ('reportNumber', models.IntegerField()),
                ('certIssueDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.CharField(max_length=3)),
                ('clientName', models.CharField(max_length=25)),
                ('clientType', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationID', models.IntegerField()),
                ('address1', models.CharField(max_length=25)),
                ('address2', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('postalCode', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('phoneNumber', models.CharField(max_length=25)),
                ('faxNumber', models.CharField(max_length=25)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxSystemVoltage', models.IntegerField()),
                ('voc', models.IntegerField()),
                ('isc', models.IntegerField()),
                ('vmp', models.IntegerField()),
                ('imp', models.IntegerField()),
                ('pmp', models.IntegerField()),
                ('ff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNum', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('cellTechnology', models.CharField(max_length=25)),
                ('cellManufacturer', models.CharField(max_length=25)),
                ('numberOfCells', models.IntegerField()),
                ('numberOfCellsInSeries', models.IntegerField()),
                ('numberOfSeriesStrings', models.IntegerField()),
                ('numberOfDiodes', models.IntegerField()),
                ('productLength', models.FloatField(max_length=25)),
                ('productWidth', models.FloatField(max_length=25)),
                ('productWeigtht', models.FloatField(max_length=25)),
                ('superstrateType', models.CharField(max_length=25)),
                ('superstrateManufacturer', models.CharField(max_length=25)),
                ('substrateType', models.CharField(max_length=25)),
                ('substrateManufacturer', models.CharField(max_length=25)),
                ('frameType', models.CharField(max_length=25)),
                ('frameAdhesive', models.CharField(max_length=25)),
                ('encapsulantType', models.CharField(max_length=25)),
                ('encapsulantManufacturer', models.CharField(max_length=25)),
                ('junctionBoxType', models.CharField(max_length=25)),
                ('junctionBoxManufacturer', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceID', models.CharField(max_length=25)),
                ('serviceName', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('isFIrequired', models.BooleanField()),
                ('fiFrequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SequenceID', models.CharField(max_length=25)),
                ('SequenceName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testStandardID', models.IntegerField()),
                ('standardName', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('publishedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=25)),
                ('firstName', models.CharField(max_length=15)),
                ('middlleName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('jobTitle', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('officePhone', models.CharField(max_length=15)),
                ('cellPhone', models.CharField(max_length=15)),
                ('prefix', models.CharField(max_length=10)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='testStandardID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TestStandard'),
        ),
        migrations.AddField(
            model_name='performancedata',
            name='modelNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
        migrations.AddField(
            model_name='performancedata',
            name='testSequenceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TestSequence'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='locationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Location'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='testStandard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TestStandard'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
    ]
